### PR TITLE
Add an option to override value for empty result set

### PR DESCRIPTION
**Pull request by guillaumelecerf**

### CODE REVIEW

**Comment by raffis** [comment]
Thanks for the contribution @guillaumelecerf , can you add a test case for this? should be fairly simple 👍🏻

**Comment by guillaumelecerf** [comment]
@raffis : here is a new version allowing to override empty result set with an arbitrary value. I also added a simple unittest.

**Comment by guillaumelecerf** [comment]
@raffis : thanks for the merge. Would it be possible for you to create a beta version (available on DockerHub) ?

**Comment by raffis** [comment]
> @raffis : thanks for the merge. Would it be possible for you to create a beta version (available on DockerHub) ?

Yes will release any minute.

**Comment by raffis** [comment]
> > @raffis : thanks for the merge. Would it be possible for you to create a beta version (available on DockerHub) ?
> 
> Yes will release any minute.

You can test it using v1.0.0-beta8

**Comment by guillaumelecerf** [comment]
Thanks a lot, it works as expected :+1:

**Pull request merged**
